name: say_what
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.13
  - pip:
      - auditok==0.2.0
      - numpy==1.26.4
      - pandas==2.2.2
      - soundfile==0.12.1
      - transformers==4.33.3
      - huggingface-hub==0.21.4
      - openai-whisper==20231117
      - whisper-timestamped==1.15.3
      - google-cloud==0.34.0
      - google-cloud-storage==2.16.0
      - librosa==0.10.1
  
     
